spring.profiles.active=default
spring.jpa.show-sql = true
spring.mvc.hidden-method.filter.enabled=true
spring.liquibase.change-log=classpath:db/changelog/changelog.yaml
spring.liquibase.enabled=true

spring.jpa.hibernate.ddl-auto=validate
